from typing import Dict, Any

# AUTOMATICALLY GENERATED BY GOVERNANCE TRANSPILER


def check_slippage_risk(context: Dict[str, Any] = {}, event: Dict[str, Any] = {}) -> bool:
    '''
    Enforces H-Slippage: Blocks market orders exceeding 0.01 of daily volume.
    Condition: order_type==MARKET
    '''
    order_type = context.get("order_type", "MARKET")
    order_size = float(context.get("order_size", 0))
    daily_vol = float(context.get("daily_volume", 1000000))

    if order_type == "MARKET" and order_size > (daily_vol * 0.01):
        # UCA Detected: Wrong Order
        return False

    return True


def check_drawdown_limit(context: Dict[str, Any] = {}, event: Dict[str, Any] = {}) -> bool:
    '''
    Enforces H-Drawdown: Blocks buy orders if drawdown > 4.5%.
    '''
    current_drawdown = float(context.get("drawdown_pct", 0))
    if current_drawdown > 4.5:
        return False
    return True
