# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/gateway/protos/gateway.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/gateway/protos/gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n src/gateway/protos/gateway.proto\x12\x07gateway\"(\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\xc1\x01\n\x0b\x43hatRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\"\n\x08messages\x18\x02 \x03(\x0b\x32\x10.gateway.Message\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x1a\n\x12system_instruction\x18\x04 \x01(\t\x12\x0c\n\x04mode\x18\x05 \x01(\t\x12\x13\n\x0bguided_json\x18\x06 \x01(\t\x12\x14\n\x0cguided_regex\x18\x07 \x01(\t\x12\x15\n\rguided_choice\x18\x08 \x01(\t\"^\n\x0c\x43hatResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12\x14\n\x0cinput_tokens\x18\x03 \x01(\x05\x12\x15\n\routput_tokens\x18\x04 \x01(\x05\"5\n\x0bToolRequest\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x13\n\x0bparams_json\x18\x02 \x01(\t\"=\n\x0cToolResponse\x12\x0e\n\x06output\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t2\x80\x01\n\x07Gateway\x12\x37\n\x04\x43hat\x12\x14.gateway.ChatRequest\x1a\x15.gateway.ChatResponse\"\x00\x30\x01\x12<\n\x0b\x45xecuteTool\x12\x14.gateway.ToolRequest\x1a\x15.gateway.ToolResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.gateway.protos.gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=45
  _globals['_MESSAGE']._serialized_end=85
  _globals['_CHATREQUEST']._serialized_start=88
  _globals['_CHATREQUEST']._serialized_end=281
  _globals['_CHATRESPONSE']._serialized_start=283
  _globals['_CHATRESPONSE']._serialized_end=377
  _globals['_TOOLREQUEST']._serialized_start=379
  _globals['_TOOLREQUEST']._serialized_end=432
  _globals['_TOOLRESPONSE']._serialized_start=434
  _globals['_TOOLRESPONSE']._serialized_end=495
  _globals['_GATEWAY']._serialized_start=498
  _globals['_GATEWAY']._serialized_end=626
# @@protoc_insertion_point(module_scope)
