# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nemo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nemo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnemo.proto\x12\ngovernance\"4\n\rVerifyRequest\x12\r\n\x05input\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontext_json\x18\x02 \x01(\t\"2\n\x0eVerifyResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2S\n\x0eNeMoGuardrails\x12\x41\n\x06Verify\x12\x19.governance.VerifyRequest\x1a\x1a.governance.VerifyResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nemo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERIFYREQUEST']._serialized_start=26
  _globals['_VERIFYREQUEST']._serialized_end=78
  _globals['_VERIFYRESPONSE']._serialized_start=80
  _globals['_VERIFYRESPONSE']._serialized_end=130
  _globals['_NEMOGUARDRAILS']._serialized_start=132
  _globals['_NEMOGUARDRAILS']._serialized_end=215
# @@protoc_insertion_point(module_scope)
