# scripts/causal_policy_induction.py
import numpy as np
import os
import sys

# Ensure src is in path
sys.path.append(os.getcwd())

from src.causal.engine import scm_engine

def induce_policy():
    print("--- Starting Causal Policy Induction ---")

    # Configuration
    # We want to find the Tenure threshold where Blocking causes > 45% Churn Risk
    RISK_LIMIT = 0.45
    ACTION_BLOCK_FRICTION = 0.9

    # Search Space: Tenure from 0 to 10 years
    tenure_range = np.arange(0, 10.5, 0.5)

    safety_threshold = None

    print(f"Analyzing impact of 'BLOCK' action across Tenure (Limit: {RISK_LIMIT})...")

    for tenure in tenure_range:
        # Context: We isolate Tenure. Other factors nominal.
        context = {
            "Transaction_Amount": 100.0,
            "Location_Mismatch": 0,
            "Fraud_Risk": 0.5, # Moderate risk, where we might consider blocking
            "Tenure_Years": float(tenure)
        }

        # Simulate 'Block' (High Friction)
        intervention = {"Customer_Friction": ACTION_BLOCK_FRICTION}

        churn_prob = scm_engine.simulate_intervention(
            context=context,
            intervention=intervention,
            target_variable="Churn_Probability",
            num_samples=20
        )

        print(f"   Tenure: {tenure:.1f}y -> Induced Churn: {churn_prob:.4f}")

        if churn_prob > RISK_LIMIT:
            safety_threshold = tenure
            print(f"   !!! VIOLATION FOUND at Tenure >= {tenure}y")
            break

    # Generate Rego
    if safety_threshold is not None:
        print(f"--- Generating Policy: Deny Block if Tenure >= {safety_threshold} ---")

        rego_content = f"""package banking.governance

# AUTO-GENERATED BY CAUSAL INDUCTION ENGINE
# Source: scripts/causal_policy_induction.py
# Timestamp: {np.datetime64('now')}
# Logic: Blocking users with Tenure >= {safety_threshold} causes Churn Risk > {RISK_LIMIT}

deny[msg] {{
    input.action == "block_transaction"
    input.tenure_years >= {safety_threshold}
    msg := "Unsafe Control Action: Blocking high-tenure user causes unacceptable churn risk (>{RISK_LIMIT})."
}}
"""
        os.makedirs("policies", exist_ok=True)
        with open("policies/generated_causal_rules.rego", "w") as f:
            f.write(rego_content)
        print("✅ Policy Artifact Saved: policies/generated_causal_rules.rego")

    else:
        print("✅ No safety violations found in search space. No restrictions generated.")

if __name__ == "__main__":
    induce_policy()
