project_id    = "laah-cybernetics"
region        = "us-central1"
zone          = "us-central1-a"
gateway_image = "us-central1-docker.pkg.dev/laah-cybernetics/governance-stack/gateway:latest"
gpu_type      = "nvidia-tesla-t4"
machine_type  = "n1-standard-4"
enable_telemetry = "true"
trace_content = "true"
