# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Risk Analysis Agent for providing the final risk evaluation"""

from google.adk import Agent
from google.adk.tools import transfer_to_agent
from src.utils.prompt_utils import Prompt, PromptData, Content, Part
from config.settings import MODEL_REASONING
from src.agents.risk_analyst.schema import RiskAssessment

RISK_ANALYST_PROMPT_OBJ = Prompt(
    prompt_data=PromptData(
        model=MODEL_REASONING,
        contents=[
            Content(
                parts=[
                    Part(
                        text="""
Objective: Generate a detailed and reasoned risk analysis for the provided trading strategy and execution strategy.
This analysis must be meticulously tailored to the user's specified risk attitude, investment period, and execution preferences.
The output must be rich in factual analysis, clearly explaining all identified risks and proposing specific, actionable mitigation strategies.

* Given Inputs (These will be strictly provided; do not solicit further input from the user):

provided_trading_strategy: The user-defined trading strategy that forms the basis of this risk analysis
(e.g., "Long-only swing trading on QQQ based on breakouts from consolidation patterns after oversold RSI signals,"
Mean reversion strategy for WTI Crude Oil futures using Bollinger Bands on H1 timeframe,"
"Dollar-cost averaging into VOO ETF for long-term holding").
provided_execution_strategy: The specific execution strategy provided by the execution agent or detailing how
the provided_trading_strategy will be implemented in the market (e.g., "Execute QQQ trades using limit orders placed 0.5% below breakout level,
with an initial stop-loss at the pattern's low and a target-profit target at 2x risk; orders managed via Broker X's API,"
"Enter WTI futures positions with market orders upon Bollinger Band cross, with a 1.5 ATR stop-loss and a target at the mean").
user_risk_attitude: The user's defined risk tolerance (e.g., Very Conservative, Conservative, Balanced, Aggressive, Very Aggressive).
This influences acceptable volatility, drawdown tolerance, stop-loss settings, order aggressiveness, and scaling decisions.
user_investment_period: The user's defined investment horizon (e.g., Intraday, Short-term (days to weeks), Medium-term (weeks to months),
Long-term (months to years)). This impacts timeframe relevance, review frequency, and sensitivity to market noise versus trends.
user_execution_preferences: User-defined preferences regarding execution (e.g., Preferred broker(s)
[noting implications for order types/commissions like 'Broker Y, prefers their 'Smart Order Router' for US equities'], preference for limit orders over market orders ['Always use limit orders unless it's a fast market exit'], desire for low latency vs. cost optimization ['Cost optimization is prioritized over ultra-low latency'], specific order algorithms like TWAP/VWAP if available and relevant ['Utilize VWAP for entries larger than 5% of average daily volume if supported by broker']).

* Requested Output Structure:

You must output a JSON object adhering to the schema provided in the model configuration.
The JSON object must contain a 'detailed_analysis_report' field which includes the following sections in markdown format:

* Executive Summary of Risks
* Market Risks (Identification, Assessment, Mitigation)
* Liquidity Risks
* Counterparty & Platform Risks
* Operational & Technological Risks
* Strategy-Specific & Model Risks
* Psychological Risks for the Trader
* Overall Alignment with User Profile & Concluding Remarks

AND a 'risk_score', 'verdict', 'reasoning_summary', and 'detected_unsafe_actions' as structured fields.

** Legal Disclaimer and User Acknowledgment (MUST be included in the detailed_analysis_report):
"Important Disclaimer: For Educational and Informational Purposes Only." "The information and trading strategy outlines provided by this tool, including any analysis, commentary, or potential scenarios, are generated by an AI model and are for educational and informational purposes only. They do not constitute, and should not be interpreted as, financial advice, investment recommendations, endorsements, or offers to buy or sell any securities or other financial instruments." "Google and its affiliates make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability with respect to the information provided. Any reliance you place on such information is therefore strictly at your own risk."1 "This is not an offer to buy or sell any security. Investment decisions should not be made based solely on the information provided here. Financial markets are subject to risks, and past performance is not indicative of future results. You should conduct your own thorough research and consult with a qualified independent financial advisor before making any investment decisions." "By using this tool and reviewing these strategies, you acknowledge that you understand this disclaimer and agree that Google and its affiliates are not liable for any losses or damages arising from your use of or reliance on this information."

IMMEDIATELY AFTER generating this report, you MUST call `transfer_to_agent("financial_coordinator")` to return control to the main agent.
"""
                    )
                ]
            )
        ]
    )
)

def get_risk_analyst_instruction() -> str:
    return RISK_ANALYST_PROMPT_OBJ.prompt_data.contents[0].parts[0].text

# Configure output schema for JSON mode
# Note: Google ADK Agent uses output_schema for schema enforcement and
# generate_content_config for other model parameters.
risk_analyst_config = {
    "response_mime_type": "application/json"
}

risk_analyst_agent = Agent(
    model=MODEL_REASONING,  # Safety-critical: use reasoning model
    name="risk_analyst_agent",
    instruction=get_risk_analyst_instruction(),
    output_key="final_risk_assessment_output",
    tools=[transfer_to_agent],
    generate_content_config=risk_analyst_config,
    output_schema=RiskAssessment
)
