package banking.governance

# AUTO-GENERATED BY CAUSAL INDUCTION ENGINE
# Source: scripts/causal_policy_induction.py
# Timestamp: 2026-01-23T03:13:47
# Logic: Blocking users with Tenure >= 0.0 causes Churn Risk > 0.45

deny[msg] {
    input.action == "block_transaction"
    input.tenure_years >= 0.0
    msg := "Unsafe Control Action: Blocking high-tenure user causes unacceptable churn risk (>0.45)."
}
